#!/bin/sh
set -ex

PACKAGE=ctk

VERSION=${VERSION:-$2}
TARFILE=${TARFILE:-$3}

if [ -z ${VERSION}]; then
VERSION=`dpkg-parsechangelog | sed -n -e 's/^Version: \(.*\)-[^-]*$/\1/p'`
fi

REVISION=`echo $VERSION | sed -e 's/^.*git//g'`
REVISION=4c54ae036848e51a11c895a0f432d8bf51563917

if [ -z ${TARFILE}]; then
TARFILE=${PACKAGE}_${VERSION}.orig.tar.gz
fi

FOLDER=${PACKAGE}-${VERSION}

#
# put orig.tar in ../tarballs (-> default location for svn-buildpackage)
mkdir -p ../tarballs
cd ../tarballs

git clone https://github.com/commontk/CTK.git ${FOLDER}
cd ${FOLDER}
git checkout ${REVISION}
cd ..
rm -rf ${FOLDER}/.git

GZIP="--best --no-name" tar czf ${TARFILE} ${FOLDER}
rm -rf ${FOLDER}
